# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.verticalLayoutL = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayoutL.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutL.setObjectName("verticalLayoutL")
        self.labelSongs = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.labelSongs.setFont(font)
        self.labelSongs.setObjectName("labelSongs")
        self.verticalLayoutL.addWidget(self.labelSongs)
        self.songList = QtWidgets.QListWidget(self.widget)
        self.songList.setObjectName("songList")
        item = QtWidgets.QListWidgetItem()
        self.songList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.songList.addItem(item)
        self.verticalLayoutL.addWidget(self.songList)
        self.line = QtWidgets.QFrame(self.widget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutL.addWidget(self.line)
        self.searchInput = QtWidgets.QLineEdit(self.widget)
        self.searchInput.setText("")
        self.searchInput.setObjectName("searchInput")
        self.verticalLayoutL.addWidget(self.searchInput)
        self.favOnlyCheckbox = QtWidgets.QCheckBox(self.widget)
        self.favOnlyCheckbox.setObjectName("favOnlyCheckbox")
        self.verticalLayoutL.addWidget(self.favOnlyCheckbox)
        self.comboBox_2 = QtWidgets.QComboBox(self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayoutL.addWidget(self.comboBox_2)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.verticalLayoutR = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayoutR.setContentsMargins(0, 0, 0, 0)
        self.verticalLayoutR.setObjectName("verticalLayoutR")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.songTitleLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.songTitleLabel.setFont(font)
        self.songTitleLabel.setObjectName("songTitleLabel")
        self.gridLayout.addWidget(self.songTitleLabel, 0, 0, 1, 1)
        self.favButton = QtWidgets.QPushButton(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.favButton.sizePolicy().hasHeightForWidth())
        self.favButton.setSizePolicy(sizePolicy)
        self.favButton.setMaximumSize(QtCore.QSize(60, 16777215))
        self.favButton.setObjectName("favButton")
        self.gridLayout.addWidget(self.favButton, 0, 1, 1, 1)
        self.songArtistLabel = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.songArtistLabel.setFont(font)
        self.songArtistLabel.setObjectName("songArtistLabel")
        self.gridLayout.addWidget(self.songArtistLabel, 1, 0, 1, 1)
        self.verticalLayoutR.addLayout(self.gridLayout)
        self.songTabWidget = QtWidgets.QTabWidget(self.widget1)
        self.songTabWidget.setObjectName("songTabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lyricsTextView = QtWidgets.QTextBrowser(self.tab)
        self.lyricsTextView.setObjectName("lyricsTextView")
        self.verticalLayout_4.addWidget(self.lyricsTextView)
        self.songTabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setContentsMargins(4, 4, 4, 4)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.chordsTextView = QtWidgets.QTextBrowser(self.tab_2)
        self.chordsTextView.setObjectName("chordsTextView")
        self.verticalLayout_3.addWidget(self.chordsTextView)
        self.songTabWidget.addTab(self.tab_2, "")
        self.verticalLayoutR.addWidget(self.songTabWidget)
        self.verticalLayout.addWidget(self.splitter)
        self.favOnlyCheckbox.raise_()
        self.searchInput.raise_()
        self.songTabWidget.raise_()
        self.songList.raise_()
        self.labelSongs.raise_()
        self.songTitleLabel.raise_()
        self.songArtistLabel.raise_()
        self.favButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuSong = QtWidgets.QMenu(self.menubar)
        self.menuSong.setObjectName("menuSong")
        self.menuChords = QtWidgets.QMenu(self.menubar)
        self.menuChords.setObjectName("menuChords")
        self.menuTranspose = QtWidgets.QMenu(self.menuChords)
        self.menuTranspose.setObjectName("menuTranspose")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuFont_size = QtWidgets.QMenu(self.menuView)
        self.menuFont_size.setObjectName("menuFont_size")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        MainWindow.insertToolBarBreak(self.toolBar)
        self.actionNewSong = QtWidgets.QAction(MainWindow)
        self.actionNewSong.setObjectName("actionNewSong")
        self.actionEditSong = QtWidgets.QAction(MainWindow)
        self.actionEditSong.setObjectName("actionEditSong")
        self.actionDeleteSong = QtWidgets.QAction(MainWindow)
        self.actionDeleteSong.setObjectName("actionDeleteSong")
        self.actionAddChords = QtWidgets.QAction(MainWindow)
        self.actionAddChords.setObjectName("actionAddChords")
        self.actionEditChords = QtWidgets.QAction(MainWindow)
        self.actionEditChords.setObjectName("actionEditChords")
        self.actionDeleteChords = QtWidgets.QAction(MainWindow)
        self.actionDeleteChords.setObjectName("actionDeleteChords")
        self.actionChordsChart = QtWidgets.QAction(MainWindow)
        self.actionChordsChart.setObjectName("actionChordsChart")
        self.actionTransposeUp = QtWidgets.QAction(MainWindow)
        self.actionTransposeUp.setObjectName("actionTransposeUp")
        self.actionTransposeDown = QtWidgets.QAction(MainWindow)
        self.actionTransposeDown.setObjectName("actionTransposeDown")
        self.actionTransposeReset = QtWidgets.QAction(MainWindow)
        self.actionTransposeReset.setObjectName("actionTransposeReset")
        self.actionFontBigger = QtWidgets.QAction(MainWindow)
        self.actionFontBigger.setObjectName("actionFontBigger")
        self.actionFontSmaller = QtWidgets.QAction(MainWindow)
        self.actionFontSmaller.setObjectName("actionFontSmaller")
        self.actionFontReset = QtWidgets.QAction(MainWindow)
        self.actionFontReset.setObjectName("actionFontReset")
        self.actionDuplicate = QtWidgets.QAction(MainWindow)
        self.actionDuplicate.setObjectName("actionDuplicate")
        self.menuSong.addAction(self.actionNewSong)
        self.menuSong.addAction(self.actionEditSong)
        self.menuSong.addAction(self.actionDeleteSong)
        self.menuTranspose.addAction(self.actionTransposeUp)
        self.menuTranspose.addAction(self.actionTransposeDown)
        self.menuTranspose.addAction(self.actionTransposeReset)
        self.menuChords.addAction(self.actionAddChords)
        self.menuChords.addAction(self.actionEditChords)
        self.menuChords.addAction(self.actionDeleteChords)
        self.menuChords.addAction(self.actionDuplicate)
        self.menuChords.addSeparator()
        self.menuChords.addAction(self.menuTranspose.menuAction())
        self.menuChords.addSeparator()
        self.menuChords.addAction(self.actionChordsChart)
        self.menuView.addAction(self.actionFontBigger)
        self.menuView.addAction(self.actionFontSmaller)
        self.menuView.addAction(self.actionFontReset)
        self.menuView.addAction(self.menuFont_size.menuAction())
        self.menubar.addAction(self.menuSong.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuChords.menuAction())
        self.toolBar.addAction(self.actionNewSong)

        self.retranslateUi(MainWindow)
        self.songTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ChordsHouse"))
        self.labelSongs.setText(_translate("MainWindow", "Songs"))
        __sortingEnabled = self.songList.isSortingEnabled()
        self.songList.setSortingEnabled(False)
        item = self.songList.item(0)
        item.setText(_translate("MainWindow", "Robbers - the 1975"))
        item = self.songList.item(1)
        item.setText(_translate("MainWindow", "Sunflower - Post Malone"))
        self.songList.setSortingEnabled(__sortingEnabled)
        self.searchInput.setPlaceholderText(_translate("MainWindow", "Type to search..."))
        self.favOnlyCheckbox.setText(_translate("MainWindow", "Favorites only"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "sort by title"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "sort by title"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "sort by artist"))
        self.songTitleLabel.setText(_translate("MainWindow", "Robbers"))
        self.favButton.setToolTip(_translate("MainWindow", "add to favorite"))
        self.favButton.setText(_translate("MainWindow", "+ Fav"))
        self.songArtistLabel.setText(_translate("MainWindow", "The 1975"))
        self.lyricsTextView.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial,sans-serif\'; color:#423f42;\">She had a face straight out of magazine<br />God only knows but you\'ll never leave her<br />Her balaclava is starting to chafe<br />And when she gets his gun he\'s begging<br />Babe, stay, stay, stay<br />(Stay, stay, stay)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'arial,sans-serif\'; color:#423f42;\"><br /></p></body></html>"))
        self.songTabWidget.setTabText(self.songTabWidget.indexOf(self.tab), _translate("MainWindow", "Lyrics"))
        self.comboBox.setItemText(0, _translate("MainWindow", "version 1"))
        self.chordsTextView.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'arial,sans-serif\'; color:#423f42;\">She had a face straight out of magazine<br />God only knows but you\'ll never leave her<br />Her balaclava is starting to chafe<br />And when she gets his gun he\'s begging<br />Babe, stay, stay, stay<br />(Stay, stay, stay)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'arial,sans-serif\'; color:#423f42;\"><br /></p></body></html>"))
        self.songTabWidget.setTabText(self.songTabWidget.indexOf(self.tab_2), _translate("MainWindow", "Chords"))
        self.menuSong.setTitle(_translate("MainWindow", "Song"))
        self.menuChords.setTitle(_translate("MainWindow", "Chords"))
        self.menuTranspose.setTitle(_translate("MainWindow", "Transpose"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuFont_size.setTitle(_translate("MainWindow", "gg"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionNewSong.setText(_translate("MainWindow", "New song"))
        self.actionEditSong.setText(_translate("MainWindow", "Edit song"))
        self.actionDeleteSong.setText(_translate("MainWindow", "Delete song"))
        self.actionAddChords.setText(_translate("MainWindow", "Add new chords"))
        self.actionEditChords.setText(_translate("MainWindow", "Edit"))
        self.actionDeleteChords.setText(_translate("MainWindow", "Delete"))
        self.actionChordsChart.setText(_translate("MainWindow", "See chords chart"))
        self.actionTransposeUp.setText(_translate("MainWindow", "+"))
        self.actionTransposeUp.setShortcut(_translate("MainWindow", "Ctrl+]"))
        self.actionTransposeDown.setText(_translate("MainWindow", "-"))
        self.actionTransposeDown.setShortcut(_translate("MainWindow", "Ctrl+["))
        self.actionTransposeReset.setText(_translate("MainWindow", "Reset"))
        self.actionTransposeReset.setShortcut(_translate("MainWindow", "Ctrl+P"))
        self.actionFontBigger.setText(_translate("MainWindow", "Bigger font"))
        self.actionFontBigger.setShortcut(_translate("MainWindow", "Ctrl+."))
        self.actionFontSmaller.setText(_translate("MainWindow", "Smaller font"))
        self.actionFontSmaller.setShortcut(_translate("MainWindow", "Ctrl+,"))
        self.actionFontReset.setText(_translate("MainWindow", "Reset font size"))
        self.actionFontReset.setShortcut(_translate("MainWindow", "Ctrl+/"))
        self.actionDuplicate.setText(_translate("MainWindow", "Duplicate"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
